# 파이썬 클래스와 객체

In [1]:
def var_arg(*args):
    print(args)
    return(sum(args))

In [2]:
var_arg(1,2,3,4,5)

(1, 2, 3, 4, 5)


15

In [3]:
def var_kwargs(**kwargs):
    print(kwargs)
    return sum([*kwargs.values()])

In [4]:
var_kwargs(a=1,b=3)

{'a': 1, 'b': 3}


4

In [5]:
def var_args(*args, **kwargs):
    print(args)
    print(kwargs)
    args = list(args) + [*kwargs.values()]
    return sum(args)

In [6]:
var_args(1,2,3,4,5,a=1,b=3)

(1, 2, 3, 4, 5)
{'a': 1, 'b': 3}


19

In [2]:
class Klass(object):
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    

In [3]:
k = Klass("객체생성")

In [4]:
k.name

'객체생성'

In [10]:
k.getName()

'객체생성'

In [5]:
isinstance(k,Klass)

True

In [6]:
Klass.__dict__

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.Klass.__init__(self, name)>,
              'getName': <function __main__.Klass.getName(self)>,
              '__dict__': <attribute '__dict__' of 'Klass' objects>,
              '__weakref__': <attribute '__weakref__' of 'Klass' objects>,
              '__doc__': None})

In [7]:
Klass.__init__

<function __main__.Klass.__init__(self, name)>

In [8]:
Klass.__init__(k,'함수로 갱신')

In [9]:
k.name

'함수로 갱신'

In [10]:
k.__init__

<bound method Klass.__init__ of <__main__.Klass object at 0x7faf291f50d0>>

In [11]:
k.__init__("메소드로 갱신")

In [12]:
k.name

'메소드로 갱신'

In [19]:
import numpy as np
ar = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

print(ar[0:, 1:])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [17]:
import pandas as pd

df = pd.DataFrame({'이름':['서준', '우현', '인아'],

'수학': [90, 80, 70],

'영어': [98, 89, 95],

'음악': [85, 95, 100],

'체육': [100, 90, 90]

})

In [18]:
df

이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

## 정수와 실수 객체만들기

In [20]:
x=1

In [21]:
isinstance(x,int)

True

In [22]:
y=1.1

In [23]:
isinstance(y,float)

True

In [24]:
a=float(1)

In [25]:
a

1.0

In [26]:
b = int(a)

In [27]:
b

1

In [28]:
float('1.1'),int('1')

(1.1, 1)

In [29]:
'1.1'.isdigit()

False

In [30]:
try:
    int('1.1')
except Exception as e:
    print(e)

invalid literal for int() with base 10: '1.1'


## 5. 문자열

### (1). 유니코드 (한글,영문)
### (2). 바이트  (영어,숫자)

In [32]:
# 유니코드
s="문자열"

#바이트
b=b"string" #앞에 b붙이기

In [33]:
isinstance(s,str),isinstance(s,bytes)

(True, False)

In [34]:
isinstance(b,str),isinstance(b,bytes)

(False, True)

### 인덱스로 문자열 검색하기

In [35]:
s[0], b[0]

('문', 115)

In [37]:
chr(b[0]) # 바이트 문자형으로 변환

's'

In [38]:
s[-1], b[-1]

('열', 103)

In [40]:
chr(b[-1])

'g'

In [41]:
try:
    s[0] = 100 #문자열을 변경불가
except Exception as e:
    print(e)

'str' object does not support item assignment


In [42]:
try:
    b[0] = 100
except Exception as e:
    print(e)

'bytes' object does not support item assignment


### 문자열 암호화

In [43]:
bs = s.encode() #문자열을 암호화해서 바이트로 만들기

In [44]:
isinstance(bs,bytes)

True

In [45]:
len(bs)

9

In [46]:
bs

b'\xeb\xac\xb8\xec\x9e\x90\xec\x97\xb4'

In [47]:
bs.decode() #다시 문자열로

'문자열'